// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpRpRhbZymeQBtEsizX4ULpaKM3769lsY',
    appId: '1:83721951163:web:8e7c979284315bc5af569e',
    messagingSenderId: '83721951163',
    projectId: 'push-noti-bba7c',
    authDomain: 'push-noti-bba7c.firebaseapp.com',
    storageBucket: 'push-noti-bba7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiNBEsVaaCThd21m33opgdbt-5Dn98VDs',
    appId: '1:83721951163:android:8e5d3376270cd6eaaf569e',
    messagingSenderId: '83721951163',
    projectId: 'push-noti-bba7c',
    storageBucket: 'push-noti-bba7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI-0J4VlLFsJ4Hyvx_lQYMkN1-uQxUjfM',
    appId: '1:83721951163:ios:c4eee06145ceef1caf569e',
    messagingSenderId: '83721951163',
    projectId: 'push-noti-bba7c',
    storageBucket: 'push-noti-bba7c.firebasestorage.app',
    iosBundleId: 'com.example.pushNoti',
  );
}
